Jwt
qiwi/inno_basic_server pull request #4
Opened 2017-02-09 07:47 UTC by dlukanin

2017-02-11 18:42 UTC, gkonnov requested changes

2017-02-11 18:42 UTC, GEGman commented on app/models/users.ts
> +            ' FROM koa.obj_user WHERE user_email = $1', [email]);
Надо будет подумать, как это вообще потом в модуль вынести вроде, inno_auth_ts и без koa.

2017-02-11 18:42 UTC, GEGman commented on app/models/users.ts
> +        return Hash.getSha256(password) === user.user_password;
Не нравится мне, что мы из базы пароль достаем и сравниваем. Может утечь. Лучше всего в sql сравнивать напрямую. Безопасней и проще. Из getItemByEmail пароль лучше убрать.

2017-02-11 18:42 UTC, GEGman commented on app/models/users.ts
> +    public async checkUser(email: string, password: string): Promise<boolean> {
Либо везде Item, либо User. Лучше, наверное User в данном случае. :)

2017-02-11 18:42 UTC, GEGman commented on app/routes.ts
> +    .post(config.get('url') + 'public/auth/login/', auth.login);
А почему тут /public/auth/login, а там users/remove ?

2017-02-11 18:42 UTC, GEGman commented on app/routes.ts
> +    .post(userBaseRoute + 'remove', users.deleteItem)
Предлагаю из канонического примера убрать удаление пользователей. Такой операции никогда не будет. Только логическое если. :)

2017-02-12 22:09 UTC, dlukanin commented on app/models/users.ts
> +        return Hash.getSha256(password) === user.user_password;
user_password такой же атрибут сущности юзер, как и другие поля. куда утечет и что с хэшом с солью кто сделает?

2017-02-12 22:12 UTC, dlukanin commented on app/routes.ts
> +    .post(userBaseRoute + 'remove', users.deleteItem)
удаления никогда не будет? даже safe delete? чот слабо верится

2017-02-12 22:12 UTC, dlukanin commented on app/routes.ts
> +    .post(config.get('url') + 'public/auth/login/', auth.login);
ага, ок

2017-03-09 11:33 UTC, Khromushkin commented
Нужно в sample конфиг добавить пример работы с jwt

2018-03-27 12:00 UTC, closed without merging